### ISSUE TITLE
steg86 does not compile.

### ISSUE THREAD

**Issue by caedmon-kitty** [woodruffw/steg86#12]
$ rustc --version
rustc 1.43.1
$ cargo install steg86

Results in a number of errors regarding "with_name".  All are similar to this one:
[steg86-compile-errors.log](https://github.com/woodruffw/steg86/files/5328495/steg86-compile-errors.log)

 Compiling steg86 v0.1.1
error[E0599]: no function or associated item named `with_name` found for struct `clap::build::arg::Arg<'_>` in the current scope
  --> /home/michaelr/.cargo/registry/src/github.com-1ecc6299db9ec823/steg86-0.1.1/src/main.rs:19:26
   |
19 |                     Arg::with_name("input")
   |                          ^^^^^^^^^
   |                          |
   |                          function or associated item not found in `clap::build::arg::Arg<'_>`
   |                          help: there is a method with a similar name: `get_name`

**Comment by woodruffw** [comment]
Yep, this looks like an incompatibility between `clap` betas. Will fix in a bit.

**Comment by woodruffw** [comment]
Just released 0.1.2, which should fix the build issues.

**Comment by caedmon-kitty** [comment]
Thank you for the quick fix!

**Comment by woodruffw** [comment]
No problem, thanks for reporting it!
