### ISSUE TITLE
Consult a lawyer about current license

### ISSUE THREAD

**Issue by ssokolow** [woodruffw/steg86#2]
I'm not a lawyer, but I've had enough experience with software licensing that I'd be wary of the current license without consulting one.

Slapping restrictions on base licenses that have passages like "without restriction, including without limitation" can have unintended side-effects. (And you *don't* want to rephrase existing license text without an expert who knows the precedents for how different phrasings have been interpreted by the courts in the past.)

...though, admittedly, I'm more familiar with how they show up in licenses like the GPL or some Creative Commons licenses, where you run into things like explicit "you may not add additional restrictions" (GPL2) or "additional restrictions are invalid and may be ignored" (GPL3) clauses, combined with things like "the text of this license is licensed to you under the condition you do not modify it" (GPL) or "the name of this license is a trademark that is only licensed to you for use with the un-modified text of our version of this license" (Creative Commons).

In the GPL2 example, a GPL2 license with additional restrictions is equivalent to All Rights Reserved because it's impossible to satisfy all the terms simultaneously. That's why the GPL3 changed it to "If someone tries to slap additional restrictions on this, they're invalid and may be ignored".

In the Creative Commons example, trademark law prevents you from mentioning Creative Commons when making a derivative license for the same reason that commercials say "the next leading brand". (You're not allowed to use someone's trademark to promote a competitor without their permission and riding on the name-recognition of the license you derived from counts.)

...plus, of course, the usual concerns:

1. Often, to save legal costs and paperwork, companies will refuse anything that's not an *exact* match for the licenses they've already OKed, which means that other people will then do likewise to ensure that their creations' aren't hampered in their ability to get popular by dependencies with such "toxic" licenses.
2. People tend to look unfavourably on licenses which don't get approved by one of the OSI, the FSF, or Debian legal, and the Open Source Definition, the Free Sofware Foundation's Four Software Freedoms, and the Debian Free Software Guidelines all forbid restrictions on fields of endeavour. (Not that I'm telling you to change it. Just being thorough in giving you context.)

**Comment by woodruffw** [comment]
Thanks for raising these concerns. I haven't consulted a lawyer over my custom license, although I might in the future (and will update my projects if they raise issues around the legality of the terms).

In the mean time: most people should treat this (and other projects licensed under the same terms) as "source available," not "open source" per any OSI/FSF/whatever definition. I'm perfectly content to not have any large companies attempt to use this project, or most of my others :slightly_smiling_face:

**Comment by ssokolow** [comment]
Fair enough. My main concern is that the permission to use it in binary form is contingent on the same license.

I'm a bit paranoid about my software so, if I were to want to use this, I might try my hand at clean-room re-creating it from the description of the technique in the README.

**Comment by woodruffw** [comment]
> Fair enough. My main concern is that the permission to use it in binary form is contingent on the same license.

It is, yes. 

> I'm a bit paranoid about my software so, if I were to want to use this, I might try my hand at clean-room re-creating it from the description of the technique in the README.

Feel free! The Hydan paper is also an excellent reference.

**Comment by ssokolow** [comment]
> The Hydan paper is also an excellent reference.

Thanks. :)
