### ISSUE TITLE
Dependancy problem for version 0.1.2

### ISSUE THREAD

**Issue by kaetir** [woodruffw/steg86#254]
The program does not work (pannics) with de latest version of the dependencies

Fixing clap and iced to the following version in the cargo.toml fixes the issue

clap = "=3.0.0-beta.2"
iced-x86 = "=1.12.0"

**Comment by woodruffw** [comment]
Thanks for the report -- version 0.1.2 is very old, and there have been 4 years of releases since then. Is there a reason you're using an older version?

**Comment by kaetir** [comment]
Some CTF challenge relies on it...

The crates.io version does not install with `cargo install steg86@0.1.2`

So I though that leaving a hint for people who want to solve the challenge would be nice. :smile:

**Comment by woodruffw** [comment]
> Some CTF challenge relies on it...
> 
> 
> 
> The crates.io version does not install with `cargo install steg86@0.1.2`
> 
> 
> 
> So I though that leaving a hint for people who want to solve the challenge would be nice. :smile:  

Those CTF challenges should be updated to use a newer version :-) 

Still, thank you for documenting this. I'm going to close this out since it should now be indexed by search engines.
