### ISSUE TITLE
"steg86 extract" produces "Fatal: incompatible steg86 version (expected 1, got 0)"

### ISSUE THREAD

**Issue by PierrickPochelu** [woodruffw/steg86#284]
Hello,

Thanks for developing steg86.

I am trying to solve this challenge using steg86 : https://www.root-me.org/fr/Challenges/Steganographie/ELF-x64-Duality

The organizers share the file `innocent.bin`. I would like to use steg86 on this file.

Below my command and error:

```
$ steg86 profile ./innocent.bin
Summary for ./innocent.bin:
	18390 total instructions
	3110 potential semantic pairs
	5 potential commutative instructions
	3083 bits of information capacity (385 bytes, approx. 0KB)
$ steg86 extract ./innocent.bin > msg.txt
Fatal: incompatible steg86 version (expected 1, got 0)
```

I tried to install older version (e.g., 0.1.1) but cargo raises this error:
```
$ cargo install --version 0.1.1  steg86
[...]
   Compiling steg86 v0.1.1
error[E0599]: no function or associated item named `with_reg_reg` found for struct `Instruction` in the current scope
[...]
```

Regards,
Pierrick

**Comment by woodruffw** [comment]
Hi @PierrickPochelu, please see #99 -- you need to pass `--locked` to ensure that `cargo` honors the project's exact locked deps if you want to install an older version.
