### ISSUE TITLE
Fatal: incompatible steg86 version (expected 1, got 0)

### ISSUE THREAD

**Issue by k-redas** [woodruffw/steg86#84]
Hello,

Thanks for you tool :-)

Just I have problem when I want to extract hidden message.

Steg86 return : "Fatal: incompatible steg86 version (expected 1, got 0)"

Some help ?

TY

**Comment by woodruffw** [comment]
We bumped steg86's encoding format version with the most recent release series.

You'll need to use an earlier release (pre `0.2.0`) for versions prior to `1`.
