### ISSUE TITLE
Fatal: incompatible steg86 version (expected 1, got 0)

### ISSUE THREAD

**Issue by clsergent** [woodruffw/steg86#99]
I recently tried to extract a message using steg86 v0.2.0 which failed with this error:
_Fatal: incompatible steg86 version (expected 1, got 0)_
I tried to install an older version of steg86 (either using cargo or from source) but I encountered errors (mainly E0308 and E0599).

Is there a way to solve this issue?
Thanks

**Comment by woodruffw** [comment]
Could you try `cargo install --locked` with one of the older versions? Cargo doesn't respect lockfiles by default for `cargo install`, which causes pain like this.

**Comment by woodruffw** [comment]
See also: https://github.com/woodruffw/steg86/issues/12

**Comment by clsergent** [comment]
Adding `--locked` fixed my issues. Thanks for you quick reply!
